

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.
fib_prev = 1
fib_cur = 2

puts "\nPlease enter a limiting value: \n \n"
limit = gets.chomp
puts "\n"

sum = 0

while fib_cur < limit.to_i
	if fib_cur%2==0
		puts '(' + fib_cur.to_s + ')'
		sum += fib_cur
	end
	puts fib_cur.to_s
	holder = fib_prev
	fib_prev = fib_cur
	fib_cur += holder
end

puts "\nThe sum of all even-valued Fibonacci values under " + limit + ' is equal to ' + sum.to_s + ".\n "

